### ISSUE TITLE
eslint is not loaded

### ISSUE THREAD

**Issue by kaizer1v** [gramener/eslint-plugin-template#1]
When I try to use eslint --ext html . from the shell - it throws the following error
Also, I have installed another plugin called [eslint-plugin-html](https://www.npmjs.com/package/eslint-plugin-html). Not sure if the other plugin has any compatibility issues with your plugin, but here is the plugins section of the .eslintrc.json file

```javascript
"plugins": [
    "template"
]
```
which causes the below error. When the option "template" is removed, eslint-html runs fine, but still throws template related errors.

```
eslint-plugin-html error: It seems that eslint is not loaded. If you think it is a bug, please file a report at https://github.com/BenoitZugmeyer/eslint-plugin-html/issues
Error: eslint-plugin-html error: It seems that eslint is not loaded. If you think it is a bug, please file a report at https://github.com/BenoitZugmeyer/eslint-plugin-html/issues
    at Object.<anonymous> (/usr/local/lib/node_modules/eslint-plugin-template/node_modules/eslint-plugin-html/src/index.js:48:9)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/eslint-plugin-template/eslint-plugin-template.js:2:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by kaizer1v** [comment]
Actually this was fixed when changed the file permissions for .configstore folder.

You need to change `~/.config/configstore/` owner to your user name:
`sudo chown _username_ ~/.config/configstore`

Typically you don't want to change to root but only sudo on your server.
That should fix the permission issue problem.

Thank you.

**Comment by kaizer1v** [comment]
Actually this was fixed when changed the file permissions for `.configstore` folder.

You need to change `~/.config/configstore/` owner to your user name:
`sudo chown _username_ ~/.config/configstore`

Typically you don't want to change to root but only sudo on your server.
That should fix the permission issue problem.

Thank you.
